// Test IDs for cart, checkout, wishlist features.
export const CART = {
  drawer: 'cart-drawer',
  drawerClose: 'cart-drawer-close-button',
  drawerOverlay: 'cart-drawer-overlay',
  navCartButton: 'navbar-cart-button',
  navCartBadge: 'navbar-cart-badge',
  lineItem: 'cart-line-item',
  qtyPlus: 'cart-item-qty-plus',
  qtyMinus: 'cart-item-qty-minus',
  removeButton: 'cart-item-remove-button',
  promoInput: 'cart-promo-input',
  promoSubmit: 'cart-promo-submit-button',
  subtotal: 'cart-subtotal',
  total: 'cart-total',
  viewCartLink: 'cart-view-cart-link',
  checkoutLink: 'cart-checkout-link',
  upsellRow: 'cart-upsell-row',
  empty: 'cart-empty-state',
  page: 'cart-page',
  pageContinueShopping: 'cart-page-continue-shopping',
  addToCartCard: 'product-card-add-to-cart-button',
  addToCartPDP: 'product-detail-add-to-cart-button',
};

export const CHECKOUT = {
  page: 'checkout-page',
  stepIndicator: 'checkout-step-indicator',
  guestEmail: 'checkout-guest-email-input',
  firstName: 'checkout-first-name-input',
  lastName: 'checkout-last-name-input',
  address1: 'checkout-address1-input',
  address2: 'checkout-address2-input',
  city: 'checkout-city-input',
  state: 'checkout-state-input',
  zip: 'checkout-zip-input',
  country: 'checkout-country-input',
  shippingMethodStandard: 'checkout-shipping-standard',
  shippingMethodExpress: 'checkout-shipping-express',
  continueToPayment: 'checkout-continue-to-payment-button',
  cardNumber: 'checkout-card-number-input',
  cardExpiry: 'checkout-card-expiry-input',
  cardCvv: 'checkout-card-cvv-input',
  cardHolder: 'checkout-card-holder-input',
  paymentMethodCard: 'checkout-payment-card',
  paymentMethodPaypal: 'checkout-payment-paypal',
  paymentMethodApple: 'checkout-payment-apple',
  paymentMethodGoogle: 'checkout-payment-google',
  placeOrder: 'checkout-place-order-button',
  backToShipping: 'checkout-back-to-shipping-button',
  confirmationPage: 'order-confirmation-page',
  orderNumber: 'order-confirmation-number',
  continueShopping: 'order-confirmation-continue-shopping',
  viewOrders: 'order-confirmation-view-orders',
};

export const WISHLIST = {
  page: 'wishlist-page',
  empty: 'wishlist-empty-state',
  removeAll: 'wishlist-remove-all-button',
  cardToggle: 'product-card-wishlist-toggle',
  pdpToggle: 'product-detail-wishlist-toggle',
  navIcon: 'navbar-wishlist-button',
  navBadge: 'navbar-wishlist-badge',
};
